/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.68
 * Generated at: 2018-06-14 09:44:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.api_002dtools.console;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class console_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>千丁API接口调试系统 1.0</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/qding-api/api-tools/console/lib/themes/default/style.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/qding-api/api-tools/console/lib/themes/default-dark/style.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/qding-api/api-tools/console/lib/themes/ui-dialog.css\">\r\n");
      out.write("<style>\r\n");
      out.write("\tpre {outline: 1px solid #ccc; padding: 5px; margin: 5px; }\r\n");
      out.write("\t.string { color: green; }\r\n");
      out.write("\t.number { color: darkorange; }\r\n");
      out.write("\t.boolean { color: blue; }\r\n");
      out.write("\t.null { color: magenta; }\r\n");
      out.write("\t.key { color: red; }\r\n");
      out.write("\tol {\r\n");
      out.write("\t\tcounter-reset: li; /* Initiate a counter */\r\n");
      out.write("\t\tlist-style: none; /* Remove default numbering */\r\n");
      out.write("\t\t*list-style: decimal; /* Keep using default numbering for IE6/7 */\r\n");
      out.write("\t\tfont: 15px 'trebuchet MS', 'lucida sans';\r\n");
      out.write("\t\tpadding: 0;\r\n");
      out.write("\t\tmargin-bottom: 4em;\r\n");
      out.write("\t\ttext-shadow: 0 1px 0 rgba(255,255,255,.5);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tol ol {\r\n");
      out.write("\t\tmargin: 0 0 0 2em; /* Add some left margin for inner lists */\r\n");
      out.write("\t}\r\n");
      out.write("\t.rounded-list a{ position: relative; display: block; padding: .4em .4em .4em 2em; *padding: .4em; margin: .5em 0; background: #ddd; color: #444; text-decoration: none; border-radius: .3em; transition: all .3s ease-out; } .rounded-list a:hover{ background: #eee; } .rounded-list a:hover:before{ transform: rotate(360deg); } .rounded-list a:before{ content: counter(li); counter-increment: li; position: absolute; left: -1.3em; top: 50%; margin-top: -1.3em; background: #87ceeb; height: 2em; width: 2em; line-height: 2em; border: .3em solid #fff; text-align: center; font-weight: bold; border-radius: 2em; transition: all .3s ease-out; }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"background:#999;\">\r\n");
      out.write("\t<table style=\"width:100%\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<th style=\"width:10%;background-color:rgb(217,39,49);color:white;margin-right: 20px;\">服务<input type=\"text\" id=\"search\"/></th>\r\n");
      out.write("\t\t\t<th style=\"width:50%;background-color:rgb(217,39,49);color:white;height:40px\">描述</th>\r\n");
      out.write("\t\t\t<th style=\"width:40%;background-color:rgb(217,39,49);color:white;height:40px\">调试</th>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t\t<tbody>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td id=\"tree\" style=\"color:#999;vertical-align:top;padding:20px;\"></td>\r\n");
      out.write("\t\t\t\t<td id=\"doc\" class=\"jstree jstree-1 jstree-default-dark\" style=\"color:#999;vertical-align:top;padding:20px;\">\r\n");
      out.write("\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t<tr><td>总接口数量：</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td id=\"methodCount\"></td></tr>\r\n");
      out.write("\t\t\t\t\t\t<tr><td colspan=\"2\" id=\"vMethodCount\"></td></tr>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td class=\"jstree jstree-1 jstree-default-dark\" style=\"color:#999;vertical-align:top;padding:20px;\">\r\n");
      out.write("\t\t\t\t\t<form id=\"debugForm\">\r\n");
      out.write("\t\t\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("<tr style=\" margin-top: 20px;\"><td>数据格式</td><td><select id=\"protocolAlias\" style=\"width: 150px;height:30px; \"><option value=\"json\">json</option><option value=\"xml\">xml</option></select></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr style=\" margin-top: 20px;\"><td>请求类型</td><td><select id=\"method\" style=\"width: 150px;height:30px; \"><option value=\"get\">get</option><option value=\"post\">post</option></select></td></tr>\r\n");
      out.write("                            <tr style=\" margin-top: 20px;\"><td>请求参数</td><td></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr style=\" margin-top: 20px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea style=\" width: 410px; height: 300px;\" id=\"queryString\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr style=\" margin-top: 20px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"button\" style=\"width: 100px; text-align:center; margin-top: 20px;margin-right: 20px;\" value=\"提交请求\" id=\"debug\"/>\r\n");
      out.write("\t\t\t\t\t\t\t\t \t<input type=\"button\" value=\"查看用例\"  style=\"width: 100px; text-align:center; margin-top: 20px;\" id=\"example\">\r\n");
      out.write("\t\t\t\t\t\t\t\t \t<textarea id=\"testQuery\" style=\"display: none\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t \t<textarea id=\"testReuqest\"  style=\"display: none\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t \t<input type=\"hidden\" id=\"exampleId\"/> \r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr style=\" margin-top: 20px;\"><td>Mock Response</td><td></td></tr>\r\n");
      out.write("\t\t\t\t\t\t\t<tr style=\" margin-top: 20px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<textarea style=\" width: 410px; height: 600px;\" id=\"mockData\">mockData</textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t<div id=\"vMethodHtml\" style=\"display:none\"></div>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/qding-api/api-tools/console/lib/jquery.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/qding-api/api-tools/console/lib/jstree.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/qding-api/api-tools/console/lib/json2.js\"></script>\r\n");
      out.write("\t<script  type=\"text/javascript\" src=\"/qding-api/api-tools/console/lib/dialog.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/qding-api/api-tools/console/lib/dialog-plus.js\"></script>\r\n");
      out.write("\t<script type=\"application/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t\tvar base = location.href.indexOf('qding-api') > 0 ? '/qding-api' : '';\r\n");
      out.write("\t\tvar protocolAlias,serviceAlias,methodAlias,version;\r\n");
      out.write("\t\tvar data = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${data}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(";\r\n");
      out.write("\t\tvar desc = $('#doc');\r\n");
      out.write("\t\tvar methodCount = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${methodCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(";\r\n");
      out.write("\t\tvar to = false;\r\n");
      out.write("\t\t$(\"#methodCount\").text(methodCount+\"个\");\r\n");
      out.write("\t\tvar vMethod=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vMethod}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(";\r\n");
      out.write("\t\tvar vMethodCount=\"\";\r\n");
      out.write("\t\tvar vMethods = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${vMethodNameList}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write(";\r\n");
      out.write("\t\tvar vMethodHtml=\"\";\r\n");
      out.write("\t\tvar i=0;\r\n");
      out.write("\t\t$.each(vMethod, function(key) {\r\n");
      out.write("\t\t\tvMethodCount+=\"<p><a href='javascript:void(0);' style=\\\"color:red\\\" onclick=\\\"showMethods('\"+i+\"');\\\">\"+key+\" 版本接口数:\"+vMethod[key]+\"个</a></p>\";\r\n");
      out.write("\t\t\tvar methodArray = vMethods[key]\r\n");
      out.write("\t\t\tvar methodHtml = \"<div id='v_method_\"+i+\"'><ol class=\\\"rounded-list\\\">\";\r\n");
      out.write("\t\t\t$.each(methodArray, function(i, methodInfo){\r\n");
      out.write("\t\t\t\tmethodHtml += \"<li><a href=\\\"javascript:void(0);\\\" onclick=\\\"getMethodInfo ('\"+methodInfo.serviceAlias+\"','\"+methodInfo.methodAlias+\"','\"+methodInfo.version+\"')\\\">\"+methodInfo.methodAlias+\" (\"+methodInfo.explain+\")</a></li>\";\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tmethodHtml+=\"</ol></div>\";\r\n");
      out.write("\t\t\tvMethodHtml+=methodHtml;\r\n");
      out.write("\t\t\ti++;\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"#vMethodCount\").html(vMethodCount);\r\n");
      out.write("\t\t$(\"#vMethodHtml\").append(vMethodHtml);\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script src=\"/qding-api/api-tools/console/lib/handle.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\t\r\n");
      out.write("\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
